export enum M3uLabel {
  KEY = '#EXT-X-KEY',
  TARGETDURATION = '#EXT-X-TARGETDURATION',
  MEDIA_SEQUENCE = '#EXT-X-MEDIA-SEQUENCE',
  PLAYLIST_TYPE = '#EXT-X-PLAYLIST-TYPE',
  ENDLIST = '#EXT-X-ENDLIST'
}
